Repository bylotech/api-billicopresto, pull requests merged in 2021-09, with the labels that each got.

#16 Set up authentification for the two user models
  app/controllers/concerns/accessible.rb
  app/controllers/retailers/confirmations_controller.rb
  app/controllers/retailers/omniauth_callbacks_controller.rb
  app/controllers/retailers/passwords_controller.rb
  app/controllers/retailers/registrations_controller.rb
  app/controllers/retailers/sessions_controller.rb
  app/controllers/retailers/unlocks_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/helpers/application_helper.rb
  app/models/concerns/accessible.rb
  app/models/retailer.rb
  config/routes.rb
  db/schema.rb
Labels: back, ready to merge

#19 Landing page
  app/views/devise/registrations/new.html.erb
  app/views/pages/dashboard.html.erb
Labels: front, ready to merge

#24 set up db:import_production_dump
  lib/tasks/db_import.rake
Labels: back, ready to merge

#23 Create voucher seed
  app/models/item.rb
  app/models/retailer.rb
  config/locales/seed.fr.yml
  db/migrate/20210924170405_add_target_query_to_voucher.rb
  db/migrate/20210924185607_add_discount_cents_to_voucher.rb
  db/schema.rb
  db/seeds.rb
Labels: back, ready to merge

#28 Create voucher index action
  app/controllers/vouchers_controller.rb
  app/models/voucher.rb
  app/views/vouchers/index.html.erb
  config/locales/receipts.fr .yml
  config/locales/vouchers.fr.yml
  db/migrate/20210925210757_add_status_to_vouchers.rb
  db/schema.rb
  db/seeds.rb
  package-lock.json
  package.json
  yarn.lock
Labels: back
