Repository bylotech/api-billicopresto, pull requests merged in 2021-10, with the labels that each got.

#30 Create voucher new form and action
  app/controllers/vouchers_controller.rb
  app/models/ability.rb
  app/views/vouchers/index.html.erb
  app/views/vouchers/new.html.erb
  config/locales/vouchers.fr.yml
  config/routes.rb
  db/schema.rb
Labels: back, ready to merge

#33 Create filter feature
  app/controllers/vouchers_controller.rb
  app/views/vouchers/filter.html.erb
  app/views/vouchers/index.html.erb
  config/routes.rb
Labels: back, ready to merge

#32 Clean up front back
  app/assets/.DS_Store
  app/assets/images/.DS_Store
  app/assets/images/calendar.svg
  app/assets/images/grocery.svg
  app/assets/images/house.svg
  app/assets/images/money.svg
  app/assets/images/shampoo.svg
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_sidebar.scss
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/dashboard.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shared/_retailer_navbar.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/vouchers/index.html.erb
  app/views/vouchers/show.html.erb
  config/routes.rb
  db/migrate/20210928100903_add_gender_to_users.rb
  db/schema.rb
Labels: front, ready to merge

#35 Create statistic module
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/vouchers/vouchers_controller.rb
  app/controllers/vouchers_controller.rb
  app/models/ability.rb
  app/models/retailer.rb
  app/models/voucher.rb
  app/models/voucher_target.rb
  app/models/vouchers/voucher.rb
  app/models/vouchers/voucher_target.rb
  app/services/retailers/statistics/statistic_service.rb
  config/routes.rb
  db/schema.rb
  spec/models/item_spec.rb
  spec/models/product_spec.rb
  spec/models/receipt_line_spec.rb
  spec/models/receipt_spec.rb
  spec/models/retailer_spec.rb
  spec/models/till_spec.rb
  spec/models/voucher_spec.rb
  spec/models/voucher_target_spec.rb
  spec/requests/api/v1/receipts_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/receipts_spec.rb
  spec/requests/vouchers_spec.rb
  spec/services/retailers/statistics/statistic_service_spec.rb
  spec/views/receipts/index.html.erb_spec.rb
  spec/views/receipts/show.html.erb_spec.rb
Labels: back, ready to merge

#47 Modif voucher landing stat
  app/assets/images/contact.svg
  app/assets/stylesheets/components/_landing.scss
  app/views/pages/home.html.erb
Labels: front, ready to merge

#53 Landing page update
  app/assets/stylesheets/components/_landing.scss
  app/views/pages/home.html.erb
  app/views/shared/_retailer_navbar.html.erb
  config/environments/development.rb
  config/initializers/assets.rb
Labels: front, ready to merge, must be deployed after
